OpenTSDB:
  url: http://opentsdb.net/
  description:  Classical time series database on top of HBase. Now support Cassandra and Bigtable.
  language: Java
  backends:
    - HBase
    # Bigtable and Cassandra supported added in https://github.com/OpenTSDB/opentsdb/releases/tag/v2.3.0RC1
    - Bigtable
    - Cassandra

KairosDB:
  url: https://kairosdb.github.io/
  description: Fast Time Series Database on Cassandra
  language: Java
  backends:
    - Cassandra

Heroic:
  url: https://spotify.github.io/heroic/
  description: Scalable time series database based on Bigtable, Cassandra, and Elasticsearch
  language: Java
  backends:
    - Cassandra
    - HBase
    - Bigtable
  links:
    "Monitoring at Spotify - Introducing Heroic": https://labs.spotify.com/2015/11/17/monitoring-at-spotify-introducing-heroic/

BTrDB:
  url: https://github.com/SoftwareDefinedBuildings/btrdb
  aka: Berkeley Tree Database
  description: High performance time series database designed to support high density data storage applications.
  language: Go
  backends:
    - Ceph
  links:
    "BTrDB: Optimizing Storage System Design for Timeseries Processing": https://www.usenix.org/system/files/conference/fast16/fast16-papers-andersen.pdf

Vaultaire:
  url: https://github.com/afcowie/vaultaire
  description: data vault for system metrics, backed onto Ceph
  language: Haskell
  backends:
    - Ceph
  links:
    "Design and compare vaulataire with other time series database": http://www.anchor.com.au/blog/2014/06/vaultaire-ceph-based-immutable-tsdb/

InfluxDB:
  url: https://www.influxdata.com/time-series-platform/influxdb/
  description: Scalable datastore for metrics, events, and real-time analytics https://influxdata.com
  language: Go
  backends:
    # TODO: list TSM RRD etc
    - Custom

Beringei:
  url: https://github.com/facebookincubator/beringei
  description: A high performance, in memory time series storage engine
  language: C++
  backends:
    - Memory

Khronus:
  url: https://github.com/Searchlight/khronus
  description: distributed and reactive time series database designed to store, retrieve, analyze and process a large amount of custom metrics
  language: Scala
  backends:
    - Cassandra

"Hawkular Metrics":
  url: https://github.com/hawkular/hawkular-metrics
  description: storage engine for metric data using Cassandra
  language: Java
  backends:
    - Cassandra
  # schema
  # https://github.com/hawkular/hawkular-metrics/blob/master/core/schema/src/main/resources/org/hawkular/schema/bootstrap.groovy
